@host = https://reimagined-yodel-ppqp5wvvwqwc7r9q-8080.app.github.dev


### Q1 (JPQL + param) préstamos por DNI
GET {{host}}/consultas/prestamos/cliente/45678912

### Q1 DNI inválido (400)
GET {{host}}/consultas/prestamos/cliente/123

### Q1 DNI inexistente (404)
GET {{host}}/consultas/prestamos/cliente/99999999

### Q2 (JPQL + param) ítems pendientes de un cliente
GET {{host}}/consultas/prestamos/pendientes/cliente/1

### Q2 id negativo (400)
GET {{host}}/consultas/prestamos/pendientes/cliente/-5

### Q2 id no numérico (400)
GET {{host}}/consultas/prestamos/pendientes/cliente/abc

### Q3 (JPQL + param) vencidos hoy / a una fecha
GET {{host}}/consultas/prestamos/vencidos

###
GET {{host}}/consultas/prestamos/vencidos?fecha=2026-12-31

### Q3 fecha inválida (400)
GET {{host}}/consultas/prestamos/vencidos?fecha=ayer

### Q4 (JPQL + param) libros prestados al menos N veces
GET {{host}}/consultas/libros/mas-prestados?minimo=1

### Q4 mínimo inválido (400)
GET {{host}}/consultas/libros/mas-prestados?minimo=0

### Q5 (JPQL) multas por cliente
GET {{host}}/consultas/devoluciones/multas-por-cliente

### Q6 (JPQL) ítems devueltos con daño
GET {{host}}/consultas/devoluciones/items-danados

### N1 (nativo + param) ejemplares por estado
GET {{host}}/consultas/ejemplares/estado/DISPONIBLE

### N1 estado inválido (400)
GET {{host}}/consultas/ejemplares/estado/PERDIDO

### N2 (nativo) actividad por cliente
GET {{host}}/consultas/clientes/actividad