@host = https://reimagined-yodel-ppqp5wvvwqwc7r9q-8080.app.github.dev

### Consultas por id: entidades del catálogo
GET {{host}}/autor/1

###
GET {{host}}/categoria/1

###
GET {{host}}/cliente/1

###
GET {{host}}/editorial/1

###
GET {{host}}/libro/1

### Consultas por id: préstamos y devoluciones
GET {{host}}/ejemplar/1

###
GET {{host}}/prestamo/1

###
GET {{host}}/prestamo-item/1

###
GET {{host}}/devolucion/1

###
GET {{host}}/devolucion-item/1


### Q1  préstamos por DNI
GET {{host}}/consultas/prestamos/cliente/45678912

### Q1 DNI inválido 
GET {{host}}/consultas/prestamos/cliente/123

### Q1 DNI inexistente 
GET {{host}}/consultas/prestamos/cliente/99999999

### Q2 prestamo pendientes de un cliente
GET {{host}}/consultas/prestamos/pendientes/cliente/1

### Q2 id negativo 
GET {{host}}/consultas/prestamos/pendientes/cliente/-5

### Q2 id no numérico 
GET {{host}}/consultas/prestamos/pendientes/cliente/abc

### Q3  vencidos hoy / a una fecha
GET {{host}}/consultas/prestamos/vencidos

###fecha limite
GET {{host}}/consultas/prestamos/vencidos?fecha=2026-12-31

### Q3 fecha inválida (400)
GET {{host}}/consultas/prestamos/vencidos?fecha=ayer

### Q4  libros prestados al menos N veces
GET {{host}}/consultas/libros/mas-prestados?minimo=1

### Q4 mínimo inválido (400)
GET {{host}}/consultas/libros/mas-prestados?minimo=0

### Q5 (JPQL) multas por cliente
GET {{host}}/consultas/devoluciones/multas-por-cliente

### Q6 (JPQL) ítems devueltos con daño
GET {{host}}/consultas/devoluciones/items-danados

### N1 (nativo + param) ejemplares por estado
GET {{host}}/consultas/ejemplares/estado/DISPONIBLE

### N1 estado inválido (400)
GET {{host}}/consultas/ejemplares/estado/PERDIDO

### N2 (nativo) actividad por cliente
GET {{host}}/consultas/clientes/actividad