@host = https://reimagined-yodel-ppqp5wvvwqwc7r9q-8080.app.github.dev

### 1. Crear cliente
POST {{host}}/cliente/nuevo
Content-Type: application/json

{ "nombreCompleto": "Ana Torres", "dni": "45678912", "email": "ana@correo.com" }

### 2. Crear libro
POST {{host}}/libro/nuevo
Content-Type: application/json

{ "titulo": "Cien años de soledad", "autor": "Gabriel García Márquez", "isbn": "978-84-233-5000-1" }

### 3. Crear ejemplar 1 
POST {{host}}/ejemplar/nuevo
Content-Type: application/json

{ "idLibro": 3, "codigoBarras": "EJ-0005" }

### 4. Crear ejemplar 2
POST {{host}}/ejemplar/nuevo
Content-Type: application/json

{ "idLibro": 1, "codigoBarras": "EJ-0002" }

### 5. Registrar préstamo 
POST {{host}}/prestamo/nuevo
Content-Type: application/json

{ "idCliente": 1, "items": [ { "idEjemplar": 3 } ] }

### 6. Registrar devolución (idPrestamo devuelto en el paso 5)
POST {{host}}/devolucion/nuevo
Content-Type: application/json

{ "idPrestamo": 5, "items": [ { "idEjemplar":3, "danado": true } ] }

### 7. Error: cliente que no existe (debe dar 404)
POST {{host}}/prestamo/nuevo
Content-Type: application/json

{ "idCliente": 999, "items": [ { "idEjemplar": 1 } ] }

### 8. Error: préstamo sin ítems (debe dar 400)
POST {{host}}/prestamo/nuevo
Content-Type: application/json

{ "idCliente": 1, "items": [] }

### 9. Error: ejemplar repetido 
POST {{host}}/ejemplar/nuevo
Content-Type: application/json

{ "idLibro": 1, "codigoBarras": "EJ-0001" }
