spring.application.name=libreria
spring.datasource.url=jdbc:postgresql://ep-proud-base-actpbp6d-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_XNe3Pn2yBWtT
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.connection-timeout=30000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true